NBray_group_SOA_A04/Controllers/ActionsController.cs
/*
 * PROJECT      : RESTful Web Service
 * DEVELOPERS   : Nathan Bray, Carson Kyte, Gabriel Paquette
 * CREATED DATE : 2018-11-08
 */
using System.Collections.Generic;
using System.Web.Mvc;
using NBray_group_SOA_A04.Models;

namespace NBray_group_SOA_A04.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    public class ActionsController : Controller
    {
        // GET: Actions
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult Insert()
        {
            ViewBag.productsAPI = Url.Content("~/api/products/");
            ViewBag.customersAPI = Url.Content("~/api/customers/");
            ViewBag.ordersAPI = Url.Content("~/api/orders/");
            ViewBag.cartsAPI = Url.Content("~/api/carts/");
            return View();

        }


        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult Update()
        {
            ViewBag.productsAPI = Url.Content("~/api/products/");
            ViewBag.customersAPI = Url.Content("~/api/customers/");
            ViewBag.ordersAPI = Url.Content("~/api/orders/");
            ViewBag.cartsAPI = Url.Content("~/api/carts/");
            return View();
        }


        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult Delete()
        {
            ViewBag.productsAPI = Url.Content("~/api/products/");
            ViewBag.customersAPI = Url.Content("~/api/customers/");
            ViewBag.ordersAPI = Url.Content("~/api/orders/");
            ViewBag.cartsAPI = Url.Content("~/api/carts/");
            return View();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult Search()
        {
            ViewBag.productsAPI = Url.Content("~/api/products/");
            ViewBag.customersAPI = Url.Content("~/api/customers/");
            ViewBag.ordersAPI = Url.Content("~/api/orders/");
            ViewBag.cartsAPI = Url.Content("~/api/carts/");
            ViewBag.customerOrderAPI = Url.Content("~/api/custOrders/");

            return View();
        }
        
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult Results()
        {
            /*ViewBag.productsAPI = Url.Content("~/api/products/");
            ViewBag.customersAPI = Url.Content("~/api/customers/");*/
            ViewBag.purchaseOrderAPI = Url.Content("~/api/purchaseOrders/");
            return View();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult DisplayOrders()
        {
            /*ViewBag.productsAPI = Url.Content("~/api/products/");
            ViewBag.customersAPI = Url.Content("~/api/customers/");*/
            ViewBag.purchaseOrderAPI = Url.Content("~/api/purchaseOrders/");
            return View();
        }



        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult PreUpdateSearch()
        {
            ViewBag.productsAPI = Url.Content("~/api/products/");
            ViewBag.customersAPI = Url.Content("~/api/customers/");
            ViewBag.ordersAPI = Url.Content("~/api/orders/");
            ViewBag.cartsAPI = Url.Content("~/api/carts/");
            return View();
        }

        // GET: Actions
        [HttpGet]
        public ActionResult PreUpdateSearchCustomer([System.Web.Http.FromBody] CustomerDTO customer)
        {
            ProductDTO p = new ProductDTO();
            OrderDTO o = new OrderDTO();
            CartDTO ca = new CartDTO();

            TempData["customer"] = customer;
            TempData["product"] = p;
            TempData["order"] = o;
            TempData["cart"] = ca;

            return View("PreUpdateSearch");
        }

        // GET: Actions
        [HttpGet]
        public ActionResult PreUpdateSearchProduct([System.Web.Http.FromBody] ProductDTO product)
        {
            CustomerDTO c = new CustomerDTO();
            OrderDTO o = new OrderDTO();
            CartDTO ca = new CartDTO();

            TempData["customer"] = c;
            TempData["product"] = product;
            TempData["order"] = o;
            TempData["cart"] = ca;

            return View("PreUpdateSearch");
        }

        // GET: Actions
        [HttpGet]
        public ActionResult PreUpdateSearchOrder([System.Web.Http.FromBody] OrderDTO order)
        {
            CustomerDTO c = new CustomerDTO();
            ProductDTO p = new ProductDTO();
            CartDTO ca = new CartDTO();

            TempData["customer"] = c;
            TempData["product"] = p;
            TempData["order"] = order;
            TempData["cart"] = ca;

            return View("PreUpdateSearch");
        }

        // GET: Actions
        [HttpGet]
        public ActionResult PreUpdateSearchCart([System.Web.Http.FromBody] CartDTO cart)
        {
            CustomerDTO c = new CustomerDTO();
            ProductDTO p = new ProductDTO();
            OrderDTO o = new OrderDTO();

            TempData["customer"] = c;
            TempData["product"] = p;
            TempData["order"] = o;
            TempData["cart"] = cart;

            return View("PreUpdateSearch");
        }


        // GET: Actions
        [HttpGet]
        public ActionResult DisplayOrdersSearchBody([System.Web.Http.FromBody] string orderId)
        {
            TempData["orderId"] = orderId;

            return View("DisplayOrders");
        }
        
        // GET: Actions
        [HttpPost]
        public ActionResult CustomerOrderSearch(IList<CustOrderDTO> customerOrders)
        {
            TempData["custOrders"] = customerOrders;
            return View("Search");
        }

    }
}

NBray_group_SOA_A04/Views/Actions/Delete.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<h1>Select the type of item to delete:</h1>
<div id="selectListContainer">
    <select class="form-control" onchange="showDeleteForm()" id="selectList">
        <option value="Customer">Customer</option>
        <option value="Product">Product</option>
        <option value="Order">Order</option>
        <option value="Cart">Cart</option>
    </select>
</div>
<br />

<div id="SuccessBox" class="alert alert-success" hidden>
    <ul id="SuccessList"></ul>
</div>
<div id="FailBox" class="alert alert-danger" hidden>
    <ul id="FailList"></ul>
</div>

<form id="CustomerDeleteForm" method="POST" class="well">
    <div>
        <label for="customerID">Customer ID</label>
    </div>
    <div>
        <input class="form-control" name="customerID" id="customerID" type="text" />
    </div>
    <br />
    <div>
        <p><a disabled id="custSubmit" class="btn btn-default" onclick="DeleteItem('@ViewBag.customersAPI', 0)">Submit</a></p>
    </div>
</form>

<form id="ProductDeleteForm" method="POST" class="well" hidden>
    <div>
        <label for="prodID">Product ID</label>
    </div>
    <div>
        <input class="form-control" name="prodID" id="prodID" type="text" />
    </div>
    <br />
    <div>
        <p><a disabled id="prodSubmit" class="btn btn-default" onclick="DeleteItem('@ViewBag.productsAPI', 1)">Submit</a></p>
    </div>
</form>

<form id="OrderDeleteForm" method="POST" class="well" hidden>
    <div>
        <label for="orderID">Order ID</label>
    </div>
    <div>
        <input class="form-control" name="orderID" id="orderID" type="text" />
    </div>
    <br />
    <div>
        <p><a disabled id="orderSubmit" class="btn btn-default" onclick="DeleteItem('@ViewBag.ordersAPI', 2)">Submit</a></p>
    </div>
</form>

<form id="CartDeleteForm" method="POST" class="well" hidden>
    <div>
        <label for="cartOrderID">Order ID</label>
    </div>
    <div>
        <input class="form-control" name="cartOrderID" id="cartOrderID" type="text" />
    </div>
    <div>
        <label for="cartProdID">Product ID</label>
    </div>
    <div>
        <input class="form-control" name="cartProdID" id="cartProdID" type="text" />
    </div>
    <br />
    <div>
        <p><a disabled id="cartSubmit" class="btn btn-default" onclick="DeleteItem('@ViewBag.cartsAPI', 3)">Submit</a></p>
    </div>
</form>

NBray_group_SOA_A04/Views/Actions/DisplayOrders.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var customerOrder = (List<NBray_group_SOA_A04.Models.CustOrderDTO>)TempData["custOrders"];
}
<body>
    <div>
        <table class="table table-hover" id="orderTable">
            <thead>
                <tr>
                    <th>Order ID</th>
                    <th>Customer Name</th>
                    <th>P.O. Number</th>
                    <th>Order Date</th>
                </tr>
            </thead>
            <tbody>
                @if (customerOrder != null)
                {
                    foreach (var item in customerOrder)
                    {
                        <tr>
                            <td>@item.orderId</td>
                            <td>@(item.firstName ?? "") @item.lastName</td>
                            <td>@(item.poNumber ?? "")</td>
                            <td>@item.orderDate</td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</body>

NBray_group_SOA_A04/Views/Actions/Insert.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";


}

<h3>Select the type of item to insert:</h3>
<div id="selectListContainer">
    <select class="form-control" onchange="showInsertForm()" id="selectList">
        <option value="Customer">Customer</option>
        <option value="Product">Product</option>
        <option value="Order">Order</option>
        <option value="Cart">Cart</option>
    </select>
</div>
<br />

<div id="SuccessBox" class="alert alert-success" hidden>
    <ul id="SuccessList"></ul>
</div>
<div id="FailBox" class="alert alert-danger" hidden>
    <ul id="FailList"></ul>
</div>

<div>
    <h3>Inserted Item</h3>
    <ul id="items" />
</div>

<form id="CustomerAddForm" method="POST" class="well">
    <div>
        <label for="fName">First Name</label>
    </div>
    <div>
        <input class="form-control" name="fName" id="fName" type="text" />
    </div>
    <div>
        <label for="lName">Last Name*</label>
    </div>
    <div>
        <input class="form-control" name="lName" id="lName" type="text" />
    </div>
    <div>
        <label for="pNum">Phone Number*</label>
    </div>
    <div>
        <input class="form-control" name="pNum" id="pNum" type="text" />
    </div>
    <br />
    <div>
        <p><a class="btn btn-default" onclick="AddItem('@ViewBag.customersAPI', 0)">Submit</a></p>
    </div>
</form>

<form id="ProductAddForm" method="POST" class="well" hidden>
    <div>
        <label for="prodName">Product Name*</label>
    </div>
    <div>
        <input class="form-control" name="prodName" id="prodName" type="text" />
    </div>
    <div>
        <label for="prodWeight">Product Weight*</label>
    </div>
    <div>
        <input class="form-control" name="prodWeight" id="prodWeight" type="text" />
    </div>
    <div>
        <label for="prodPrice">Product Price*</label>
    </div>
    <div>
        <input class="form-control" name="prodPrice" id="prodPrice" type="text" />
    </div>
    <div>
        <input name="inStock" id="inStock" type="checkbox" />
        <label for="inStock">In Stock*</label>
    </div>
    <br />
    <div>
        <p><a class="btn btn-default" onclick="AddItem('@ViewBag.productsAPI', 1)">Submit</a></p>
    </div>
</form>


<form id="OrderAddForm" method="POST" class="well" hidden>
    <div>
        <label for="orderCustomerID">Customer ID*</label>
    </div>
    <div>
        <input class="form-control" name="orderCustomerID" id="orderCustomerID" type="text" />
    </div>
    <div>
        <label for="orderDate">Purchase Date*</label>
    </div>
    <div>
        <input class="form-control" name="orderDate" id="orderDate" type="date" />
    </div>
    <div>
        <label for="poNumber">P.O. Number</label>
    </div>
    <div>
        <input class="form-control" name="poNumber" id="poNumber" type="text" />
    </div>
    <br />
    <div>
        <p><a class="btn btn-default" onclick="AddItem('@ViewBag.ordersAPI', 2)">Submit</a></p>
    </div>
</form>

<form id="CartAddForm" method="POST" class="well" hidden>
    <div>
        <label for="cartOrderID">Order ID*</label>
    </div>
    <div>
        <input class="form-control" name="cartOrderID" id="cartOrderID" type="text" />
    </div>
    <div>
        <label for="cartProdID">Product ID*</label>
    </div>
    <div>
        <input class="form-control" name="cartProdID" id="cartProdID" type="text" />
    </div>

    <div>
        <label for="quanity">Quantity*</label>
    </div>
    <div>
        <input class="form-control" name="quanity" id="quanity" type="text" />
    </div>
    <br />
    <div>
        <p><a class="btn btn-default" onclick="AddItem('@ViewBag.cartsAPI', 3)">Submit</a></p>
    </div>
</form>

NBray_group_SOA_A04/Views/Actions/PreUpdateSearch.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Enter an ID to search for an item:</h1>
<div id="selectListContainer">
    <select class="form-control" onchange="showIDForm()" id="selectList">
        <option value="Customer">Customer</option>
        <option value="Product">Product</option>
        <option value="Order">Order</option>
        <option value="Cart">Cart</option>
    </select>
</div>
<br />

<div id="SuccessBox" class="alert alert-success" hidden>
    <ul id="SuccessList"></ul>
</div>
<div id="FailBox" class="alert alert-danger" hidden>
    <ul id="FailList"></ul>
</div>

<form id="CustomerIDSearchForm" method="POST" class="well">
    <div>
        <label for="customerID">Customer ID</label>
    </div>
    <div>
        <input class="form-control" name="customerID" id="customerID" type="text" />
    </div>
    <br />
    <div>
        <p><a disabled id="custSubmit" class="btn btn-default" onclick="SearchID('@ViewBag.customersAPI', 0, '@Url.Action("PreUpdateSearchCustomer","Actions")')">Submit</a></p>
    </div>
</form>

<form id="ProductIDSearchForm" method="POST" class="well" hidden>
    <div>
        <label for="prodID">Product ID</label>
    </div>
    <div>
        <input class="form-control" name="prodID" id="prodID" type="text" />
    </div>
    <br />
    <div>
        <p><a disabled id="prodSubmit" class="btn btn-default" onclick="SearchID('@ViewBag.productsAPI', 1, '@Url.Action("PreUpdateSearchProduct","Actions")')">Submit</a></p>
    </div>
</form>

<form id="OrderIDSearchForm" method="POST" class="well" hidden>
    <div>
        <label for="orderID">Order ID</label>
    </div>
    <div>
        <input class="form-control" name="orderID" id="orderID" type="text" />
    </div>
    <br />
    <div>
        <p><a disabled id="orderSubmit" class="btn btn-default" onclick="SearchID('@ViewBag.ordersAPI', 2, '@Url.Action("PreUpdateSearchOrder","Actions")')">Submit</a></p>
    </div>
</form>

<form id="CartIDSearchForm" method="POST" class="well" hidden>
    <div>
        <label for="cartOrderID">Order ID</label>
    </div>
    <div>
        <input class="form-control" name="cartOrderID" id="cartOrderID" type="text" />
    </div>
    <div>
        <label for="cartProdID">Product ID</label>
    </div>
    <div>
        <input class="form-control" name="cartProdID" id="cartProdID" type="text" />
    </div>
    <br />
    <div>
        <p><a disabled id="cartSubmit" class="btn btn-default" onclick="SearchID('@ViewBag.cartsAPI', 3, '@Url.Action("PreUpdateSearchCart","Actions")')">Submit</a></p>
    </div>
</form>

NBray_group_SOA_A04/Views/Actions/Results.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    string orderId = null;

    orderId = @TempData["orderId"] as string;
}

<body>
    <label hidden id="orderId">@orderId</label>
    <div class="row">
        <h3>Customer Information</h3>
        <div class="col-md-3 pull-right float-right">
            <br />
            <div>
                <label id="resultsPurchaseDate">Purchase Date: <span style="font-weight:normal"></span></label>
            </div>
            <div>
            </div>
            <div>
                <label id="resultsPONumber">  P.O. Number:  <span style="font-weight:normal"></span></label>
            </div>
        </div>
        <div class="col-md-3">
            <div>

            </div>
            <div>
                <label id="resultsCustID">   ID:  <span style="font-weight:normal"></span></label>
            </div>
            <div>
                <label id="resultsCustName"> Name:  <span style="font-weight:normal"></span></label>
            </div>
            <div>
                <label id="resultsCustpNumber">Phone:  <span style="font-weight:normal"></span></label>
            </div>
        </div>
    </div>

    <div class="container">
        <h2>Order Information</h2>
        <table class="table table-hover table-striped">
            <thead class="thead-dark">
                <tr>
                    <th>Product ID</th>
                    <th>Product Name</th>
                    <th>Quantity</th>
                    <th>Unit Price($)</th>
                    <th>Unit Weight(kg)</th>
                </tr>
            </thead>
            <tbody id="orderProductTable">
            </tbody>
        </table>

        <table class="table-condensed">
            <thead>
                <tr>
                    <th >Sub Total</th>
                    <td id="reusltsSubTotal">$</td>
                </tr>
                <tr>
                    <th>Tax (13%)</th>
                    <td id="resultsTax">$</td>
                </tr>
                <tr>
                    <th>Total</th>
                    <td id="resultsTotal">$</td>
                </tr>
            </thead>
        </table>
    </div>
    <br/>
    <div>
        <label id="resultsTotalPieces">Total Number of Pieces in Order: <span style="font-weight:normal"></span></label>
    </div>
    <div>
        <label id="resultsTotalWeight">          Total Weight of Order: <span style="font-weight:normal"></span></label>
    </div>
</body>

@section scripts{
    <script>
        $(document).ready(function () {
            console.log()
            GetPurchaseOrder("/api/purchaseOrders/", "@orderId");
        });
    </script>
}

NBray_group_SOA_A04/Views/Actions/Search.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<h3>Select the type of item to search for:</h3>
<div id="selectListContainer">
    <select class="form-control" onchange="showSearchForm()" id="selectList">
        <option value="Customer">Customer</option>
        <option value="Product">Product</option>
        <option value="Order">Order</option>
        <option value="Cart">Cart</option>
        <option value="CustOrder">Customer/Order</option>
    </select>
    <br />
    <div class="checkbox" >
        <label id="checkBoxContainer" hidden><input id="generatePOCheck" type="checkbox" >Generate Purchase Order</label>
    </div>
</div>
<br />

<div id="SuccessBox" class="alert alert-success" hidden>
    <ul id="SuccessList"></ul>
</div>
<div id="FailBox" class="alert alert-danger" hidden>
    <ul id="FailList"></ul>
</div>

<form id="CustomerSearchForm" method="POST" class="well">
    <div>
        <label for="customerID">Customer ID</label>
    </div>
    <div>
        <input class="form-control" name="searchCustomerID" id="searchCustomerID" type="text" />
    </div>
    <div>
        <label for="fName">First Name</label>
    </div>
    <div>
        <input class="form-control" name="searchfName" id="searchfName" type="text" />
    </div>
    <div>
        <label for="lName">Last Name</label>
    </div>
    <div>
        <input class="form-control" name="searchlName" id="searchlName" type="text" />
    </div>
    <div>
        <label for="pNum">Phone Number</label>
    </div>
    <div>
        <input class="form-control" name="searchpNum" id="searchpNum" type="text" />
    </div>
    <br />
    <div>
        <p><a class="btn btn-default" id="custSubmit" onclick="SearchItem('@ViewBag.customersAPI', 0)">Submit</a></p>
    </div>
</form>

<form id="ProductSearchForm" method="POST" class="well" hidden>
    <div>
        <label for="prodID">Product ID</label>
    </div>
    <div>
        <input class="form-control" name="searchProdID" id="searchProdID" type="text" />
    </div>
    <div>
        <label for="prodName">Product Name</label>
    </div>
    <div>
        <input class="form-control" name="searchProdName" id="searchProdName" type="text" />
    </div>
    <div>
        <label for="inStock">In Stock</label>
    </div>
    <div>
        <select class="form-control" id="searchInStock">
            <option value="N/A">N/A</option>
            <option value="Yes">Yes</option>
            <option value="No">No</option>
        </select>
    </div>
    <br />
    <div>
        <p><a class="btn btn-default" id="prodSubmit" onclick="SearchItem('@ViewBag.productsAPI', 1)">Submit</a></p>
    </div>
</form>

<form id="OrderSearchForm" method="POST" class="well" hidden>
    <div>
        <label for="OrderID">Order ID</label>
    </div>
    <div>
        <input class="form-control" name="OrderID" id="searchOrderID" type="text" />
    </div>
    <div>
        <label for="orderCustomerID">Customer ID</label>
    </div>
    <div>
        <input class="form-control" name="orderCustomerID" id="searchOrderCustomerID" type="text" />
    </div>
    <div>
        <label for="orderDate">Purchase Date</label>
    </div>
    <div>
        <input class="form-control" name="orderDate" id="searchOrderDate" type="text" />
    </div>
    <div>
        <label for="poNumber">P.O. Number</label>
    </div>
    <div>
        <input class="form-control" name="poNumber" id="searchpoNumber" type="text" />
    </div>
    <br />
    <div>
        <p><a class="btn btn-default" onclick="SearchItem('@ViewBag.ordersAPI', 2)">Submit</a></p>
    </div>
</form>

<form id="CartSearchForm" method="POST" class="well" hidden>
    <div>
        <label for="cartOrderID">Order ID</label>
    </div>
    <div>
        <input class="form-control" name="cartOrderID" id="searchCartOrderID" type="text" />
    </div>
    <div>
        <label for="cartProdID">Product ID</label>
    </div>
    <div>
        <input class="form-control" name="cartProdID" id="searchCartProdID" type="text" />
    </div>
    <br />
    <div>
        <p><a class="btn btn-default" onclick="SearchItem('@ViewBag.cartsAPI', 3)">Submit</a></p>
    </div>
</form>


<form id="CustomerOrderSearchForm" method="POST" class="well" hidden>
    <div>
        <label for="customerID">Customer ID</label>
    </div>
    <div>
        <input class="form-control" name="searchCustomerOrderID" id="searchCustomerOrderID" type="text" />
    </div>
    <div>
        <label for="fName">First Name</label>
    </div>
    <div>
        <input class="form-control" name="searchCustOrderfName" id="searchCustOrderfName" type="text" />
    </div>
    <div>
        <label for="lName">Last Name</label>
    </div>
    <div>
        <input class="form-control" name="searchCustOrderlName" id="searchCustOrderlName" type="text" />
    </div>
    <div>
        <label for="pNum">Phone Number</label>
    </div>
    <div>
        <input class="form-control" name="searchCustOrderpNum" id="searchCustOrderpNum" type="text" />
    </div>
    <div>
        <label for="orderDate">Purchase Date</label>
    </div>
    <div>
        <input class="form-control" name="searchCustOrderDate" id="searchCustOrderDate" type="text" />
    </div>
    <div>
        <label for="poNumber">P.O. Number</label>
    </div>
    <div>
        <input class="form-control" name="searchCustOrderpoNumber" id="searchCustOrderpoNumber" type="text" />
    </div>
    <br />
    <div>
        <p><a class="btn btn-default" onclick="SearchItem('@ViewBag.customerOrderAPI', 4, '@Url.Action("CustomerOrderSearch", "Actions")')">Submit</a></p>
    </div>
</form>






<div class=" col-md-3">
    <div class="panel panel-primary" id="itemPannel" hidden>
        <div class="panel-heading" id="itemTypePannelHeader"></div>
        <div class="panel-body" id="itemPannelBody">

            <table class="table table-condensed" id="multiItem" hidden>
                <thead>
                    <tr id="headerRow"></tr>
                </thead>
                <tbody id="tableBody"></tbody>
            </table>

        </div>
    </div>
</div>